services:
  go-app-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_CMD: ${APP_CMD:-./cmd/web}
    container_name: new-rag-go-app-service
    restart: always
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      WEAVIATE_URL: http://weaviate:8080
      UPLOAD_DIR: /app/uploads
      OPENAI_APIKEY: ${OPENAI_APIKEY}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - weaviate

  weaviate:
    image: semitechnologies/weaviate:1.19.0
    container_name: new-rag-weaviate
    hostname: weaviate
    restart: always
    ports:
      - "${WEAVIATE_PORT:-8081}:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"

      DEFAULT_VECTORIZER_MODULE: "text2vec-openai"
      ENABLE_MODULES: "text2vec-openai"
      OPENAI_EMBEDDING_MODEL: "text-embedding-3-small"
      OPENAI_APIKEY: "${OPENAI_APIKEY}"

      UUID_ALLOW_NON_UUID: "true"
      CLUSTER_HOSTNAME: "weaviate"
      CLUSTER_JOIN: ""
    volumes:
      - ./weaviate_data:/var/lib/weaviate