# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\x05proto\"(\n\x18\x45mbeddingsMessageRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\")\n\x19\x45mbeddingsMessageResponse\x12\x0c\n\x04text\x18\x02 \x01(\t2h\n\x10\x45mbeddingService\x12T\n\x0fTextToEmbedding\x12\x1f.proto.EmbeddingsMessageRequest\x1a .proto.EmbeddingsMessageResponseB\x04Z\x02./b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\002./'
  _globals['_EMBEDDINGSMESSAGEREQUEST']._serialized_start=26
  _globals['_EMBEDDINGSMESSAGEREQUEST']._serialized_end=66
  _globals['_EMBEDDINGSMESSAGERESPONSE']._serialized_start=68
  _globals['_EMBEDDINGSMESSAGERESPONSE']._serialized_end=109
  _globals['_EMBEDDINGSERVICE']._serialized_start=111
  _globals['_EMBEDDINGSERVICE']._serialized_end=215
# @@protoc_insertion_point(module_scope)
